image: adnrv/opencv

stages:
    - nes-cpu-tests

nes-cpu-assembled-program-tests:
    stage: nes-cpu-tests
    script:
        - pip install cython pygame
        - make clean test
    artifacts:
        paths:
            # output of each emulator execution of a test program
            - log/*

nes-cpu-python-unit-tests:
    stage: nes-cpu-tests
    script:
        - pip install cython pygame
        - make clean pytest
        - python3 -m unittest emulator_timing_measurements
