image: adnrv/opencv

stages:
    - assembled-program-tests

assembled-program-tests:
    stage: assembled-program-tests
    script:
        - make test
        - "for test_script in $(ls tst/*.py); do python3 $test_script; done"
    artifacts:
        paths:
            # output of each emulator execution of a test program
            - log/*
