image: adnrv/opencv

stages:
    - nes-cpu-tests

nes-cpu-assembled-program-tests:
    stage: nes-cpu-tests
    script:
        - make test
    artifacts:
        paths:
            # output of each emulator execution of a test program
            - log/*

nes-cpu-python-unit-tests:
    stage: nes-cpu-tests
    script:
        - "for test_script in $(ls tst/*.py); do python3 $test_script; done"
